name: Build Docker image and push to ECR

on:
  push:
    branches:
      - 'tech-*'

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build-Push
    runs-on: ubuntu-latest
    environment: tech-builds
    env:
      DOCKER_IMAGE_REGISTRY: makerdao/chief-keeper

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set Docker image tag
      id: image_tag
      run: echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build, tag, and push image to ECR
      id: build-image
      run: |
        docker build -t ${{ env.DOCKER_IMAGE_REGISTRY }} .
        docker tag ${{ env.DOCKER_IMAGE_REGISTRY }} ${{ env.DOCKER_IMAGE_REGISTRY }}:${{ steps.image_tag.outputs.tag }}
        docker push ${{ env.DOCKER_IMAGE_REGISTRY }}:${{ steps.image_tag.outputs.tag }}

    - name: Display image reference
      run: echo "Pushed image ${{ env.DOCKER_IMAGE_REGISTRY }}:${{ steps.image_tag.outputs.tag }}"
