name: Build Docker image and push to ECR

on:
  push:
    branches:
      - 'tech-*'

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build-Push
    runs-on: ubuntu-latest
    environment: tech-builds
    env:
      AWS_REGION: us-east-1
      DOCKER_IMAGE_REGISTRY: makerdao/chief-keeper
      DOCKER_IMAGE_TAG: ${{ github.ref_name }}-${{ github.sha }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.GA_OIDC_EKS_PROD }}
        role-session-name: ChiefKeeperBuild
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build, tag, and push image to ECR
      id: build-image
      run: |
        docker build -t ${{ env.DOCKER_IMAGE_REGISTRY }} .
        docker tag ${{ env.DOCKER_IMAGE_REGISTRY }} ${{ env.DOCKER_IMAGE_REGISTRY }}:${{ env.DOCKER_IMAGE_TAG }}
        docker push ${{ env.DOCKER_IMAGE_REGISTRY }}:${{ env.DOCKER_IMAGE_TAG }}

    - name: Display image reference
      run: echo "Pushed image ${{ env.DOCKER_IMAGE_REGISTRY }}:${{ env.DOCKER_IMAGE_TAG }}"
